/* The following code was generated by JFlex 1.6.1 */

package plic.analyse ;

import java_cup.runtime.*;
import plic.exceptions.AnalyseLexicaleException;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>AnalyseurLexical.jflex</tt>
 */
public class AnalyseurLexical implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int commentaire = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\13\1\15\1\12\1\12\22\0\1\44\1\21\1\11"+
    "\5\0\1\32\1\33\1\16\1\24\1\43\1\25\1\0\1\14\12\1"+
    "\1\0\1\42\1\22\1\20\1\23\2\0\32\17\4\0\1\17\1\0"+
    "\1\4\1\40\1\34\1\45\1\26\1\6\2\17\1\5\2\17\1\35"+
    "\1\17\1\31\1\30\1\37\1\41\1\3\1\36\1\27\1\7\1\2"+
    "\1\17\1\10\2\17\12\0\1\15\u1fa2\0\1\15\1\15\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\5\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\4\3\1\13\1\14"+
    "\3\3\1\15\1\16\1\3\1\1\11\3\1\0\1\17"+
    "\1\1\1\20\1\21\1\22\1\23\3\3\1\24\2\3"+
    "\1\25\4\3\1\26\5\3\1\27\1\3\1\30\5\3"+
    "\1\31\7\3\1\32\14\3\1\33\3\3\1\34\1\35"+
    "\1\36\2\3\1\0\2\3\1\37\5\3\1\40\1\41"+
    "\1\0\1\3\1\42\1\43\3\3\1\44\1\0\1\45"+
    "\1\3\1\46\1\3\1\47\1\50\27\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\u0130\0\u0156\0\u017c\0\114\0\u01a2\0\u01c8\0\114\0\114"+
    "\0\114\0\114\0\u01ee\0\u0214\0\u023a\0\u0260\0\114\0\114"+
    "\0\u0286\0\u02ac\0\u02d2\0\114\0\114\0\u02f8\0\u031e\0\u0344"+
    "\0\u036a\0\u0390\0\u03b6\0\u03dc\0\u0402\0\u0428\0\u044e\0\u0474"+
    "\0\u0156\0\u049a\0\u04c0\0\114\0\114\0\114\0\u0344\0\u04e6"+
    "\0\u050c\0\u0532\0\u0344\0\u0558\0\u057e\0\u05a4\0\u05ca\0\u05f0"+
    "\0\u0616\0\u063c\0\114\0\u0662\0\u0688\0\u06ae\0\u06d4\0\u06fa"+
    "\0\u0662\0\u0720\0\u0662\0\u0746\0\u076c\0\u0792\0\u07b8\0\u07de"+
    "\0\u0662\0\u0804\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8"+
    "\0\u08e8\0\u090e\0\u0934\0\u095a\0\u0980\0\u09a6\0\u09cc\0\u09f2"+
    "\0\u0a18\0\u0a3e\0\u0a64\0\u0a8a\0\u0ab0\0\u08e8\0\u0ad6\0\u0afc"+
    "\0\u0b22\0\u0afc\0\u0afc\0\u0afc\0\u0b48\0\u0b6e\0\u0b94\0\u0bba"+
    "\0\u0be0\0\u0afc\0\u0c06\0\u0c2c\0\u0c52\0\u0c78\0\u0c9e\0\u0c78"+
    "\0\u0c78\0\u0cc4\0\u0cea\0\u0c78\0\u0c78\0\u0d10\0\u0d36\0\u0d5c"+
    "\0\u0d5c\0\u0d82\0\u0d5c\0\u0da8\0\u0d5c\0\u0dce\0\114\0\u0dce"+
    "\0\u0df4\0\u0e1a\0\u0e40\0\u0e66\0\u0e8c\0\u0eb2\0\u0ed8\0\u0efe"+
    "\0\u0f24\0\u0f4a\0\u0f70\0\u0f96\0\u0fbc\0\u0fe2\0\u1008\0\u102e"+
    "\0\u1054\0\u107a\0\u10a0\0\u10c6\0\u10ec\0\u1112\0\114";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\2\10"+
    "\1\12\2\3\1\13\1\0\1\14\1\10\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\10\1\32\1\33\2\10\1\34"+
    "\1\35\1\3\1\36\12\3\1\0\2\3\1\0\1\37"+
    "\27\3\47\0\1\4\45\0\2\40\1\41\5\40\6\0"+
    "\1\40\6\0\4\40\2\0\6\40\3\0\1\40\1\0"+
    "\10\40\6\0\1\40\6\0\1\42\3\40\2\0\6\40"+
    "\3\0\1\40\1\0\10\40\6\0\1\40\6\0\4\40"+
    "\2\0\1\40\1\43\4\40\3\0\1\40\1\0\10\40"+
    "\6\0\1\40\6\0\4\40\2\0\6\40\3\0\1\40"+
    "\1\0\3\40\1\44\1\45\3\40\6\0\1\40\6\0"+
    "\1\40\1\46\2\40\2\0\2\40\1\47\1\50\2\40"+
    "\3\0\1\40\11\51\1\52\34\51\14\0\1\53\1\0"+
    "\1\54\47\0\1\55\45\0\1\56\26\0\10\40\6\0"+
    "\1\40\6\0\1\40\1\57\1\40\1\60\2\0\1\61"+
    "\5\40\3\0\1\40\1\0\3\40\1\62\4\40\6\0"+
    "\1\40\6\0\4\40\2\0\6\40\3\0\1\40\1\0"+
    "\6\40\1\63\1\40\6\0\1\40\6\0\4\40\2\0"+
    "\6\40\3\0\1\40\1\0\10\40\6\0\1\40\6\0"+
    "\2\40\1\64\1\40\2\0\6\40\3\0\1\40\1\0"+
    "\10\40\6\0\1\40\6\0\4\40\2\0\1\40\1\65"+
    "\4\40\3\0\1\40\1\0\4\40\1\66\3\40\6\0"+
    "\1\40\6\0\4\40\2\0\6\40\3\0\1\40\1\0"+
    "\2\40\1\67\3\40\1\70\1\40\6\0\1\40\6\0"+
    "\2\40\1\71\1\40\2\0\6\40\3\0\1\40\1\0"+
    "\10\40\6\0\1\40\6\0\1\72\3\40\2\0\6\40"+
    "\3\0\1\40\14\0\1\73\32\0\10\74\6\0\1\74"+
    "\6\0\4\74\2\0\6\74\3\0\1\74\1\0\3\74"+
    "\1\75\4\74\6\0\1\74\6\0\4\74\2\0\6\74"+
    "\3\0\1\74\1\0\10\74\6\0\1\74\6\0\4\74"+
    "\2\0\3\74\1\76\2\74\3\0\1\74\1\0\10\74"+
    "\6\0\1\74\6\0\2\74\1\77\1\74\2\0\6\74"+
    "\3\0\1\74\1\0\6\74\1\100\1\74\6\0\1\74"+
    "\6\0\4\74\2\0\6\74\3\0\1\74\1\0\10\74"+
    "\6\0\1\74\6\0\3\74\1\101\2\0\6\74\3\0"+
    "\1\74\1\0\3\74\1\102\4\74\6\0\1\74\6\0"+
    "\4\74\2\0\6\74\3\0\1\74\1\0\4\74\1\103"+
    "\3\74\6\0\1\74\6\0\4\74\2\0\6\74\3\0"+
    "\1\74\1\0\10\74\6\0\1\74\6\0\2\74\1\104"+
    "\1\74\2\0\6\74\3\0\1\74\11\0\1\51\34\0"+
    "\12\53\2\0\1\53\1\0\30\53\1\0\10\74\6\0"+
    "\1\74\6\0\1\74\1\105\2\74\2\0\6\74\3\0"+
    "\1\74\1\0\2\74\1\106\5\74\6\0\1\74\6\0"+
    "\4\74\2\0\6\74\3\0\1\74\1\0\10\74\6\0"+
    "\1\74\6\0\3\74\1\107\2\0\6\74\3\0\1\74"+
    "\1\0\6\74\1\110\1\74\6\0\1\74\6\0\3\74"+
    "\1\111\2\0\6\74\3\0\1\74\1\0\3\74\1\112"+
    "\4\74\6\0\1\74\6\0\4\74\2\0\6\74\3\0"+
    "\1\74\1\0\10\74\6\0\1\74\6\0\3\74\1\113"+
    "\2\0\6\74\3\0\1\74\1\0\4\74\1\114\3\74"+
    "\6\0\1\74\6\0\4\74\2\0\6\74\3\0\1\74"+
    "\1\0\10\74\6\0\1\74\6\0\4\74\2\0\4\74"+
    "\1\115\1\74\3\0\1\74\1\0\6\74\1\116\1\74"+
    "\6\0\1\74\6\0\4\74\2\0\6\74\3\0\1\74"+
    "\1\0\10\74\6\0\1\74\6\0\4\74\2\0\4\74"+
    "\1\117\1\74\3\0\1\74\1\0\10\120\6\0\1\120"+
    "\6\0\4\120\2\0\6\120\3\0\1\120\1\0\4\120"+
    "\1\121\3\120\6\0\1\120\6\0\4\120\2\0\6\120"+
    "\3\0\1\120\1\0\10\120\6\0\1\120\6\0\1\122"+
    "\3\120\2\0\6\120\3\0\1\120\1\0\2\120\1\123"+
    "\5\120\6\0\1\120\6\0\4\120\2\0\6\120\3\0"+
    "\1\120\1\0\7\120\1\121\6\0\1\120\6\0\4\120"+
    "\2\0\6\120\3\0\1\120\1\0\10\120\6\0\1\120"+
    "\6\0\3\120\1\124\2\0\6\120\3\0\1\120\1\0"+
    "\6\120\1\125\1\120\6\0\1\120\6\0\4\120\2\0"+
    "\6\120\3\0\1\120\1\0\4\120\1\126\3\120\6\0"+
    "\1\120\6\0\4\120\2\0\6\120\3\0\1\120\1\0"+
    "\4\120\1\127\3\120\6\0\1\120\6\0\4\120\2\0"+
    "\6\120\3\0\1\120\1\0\10\120\6\0\1\120\6\0"+
    "\1\120\1\130\2\120\2\0\6\120\3\0\1\120\1\0"+
    "\1\120\1\131\6\120\6\0\1\120\6\0\4\120\2\0"+
    "\6\120\3\0\1\120\1\0\10\120\6\0\1\120\6\0"+
    "\4\120\2\0\2\120\1\132\3\120\3\0\1\120\1\0"+
    "\10\120\6\0\1\120\6\0\2\120\1\133\1\120\2\0"+
    "\6\120\3\0\1\120\1\0\1\120\1\134\6\120\6\0"+
    "\1\120\6\0\4\120\2\0\6\120\3\0\1\120\1\0"+
    "\10\120\6\0\1\120\6\0\4\120\2\0\1\120\1\135"+
    "\4\120\3\0\1\120\1\0\2\120\1\136\5\120\6\0"+
    "\1\120\6\0\4\120\2\0\6\120\3\0\1\120\1\0"+
    "\10\120\6\0\1\120\6\0\4\120\2\0\3\120\1\137"+
    "\2\120\3\0\1\120\1\0\10\140\6\0\1\140\6\0"+
    "\4\140\2\0\6\140\3\0\1\140\1\0\10\140\6\0"+
    "\1\140\6\0\1\140\1\141\2\140\2\0\6\140\3\0"+
    "\1\140\1\0\10\140\6\0\1\140\6\0\4\140\2\0"+
    "\2\140\1\142\3\140\3\0\1\140\1\0\10\140\6\0"+
    "\1\140\6\0\1\140\1\143\2\140\2\0\6\140\3\0"+
    "\1\140\1\0\2\140\1\144\5\140\6\0\1\140\6\0"+
    "\4\140\2\0\6\140\3\0\1\140\1\0\10\140\6\0"+
    "\1\140\6\0\1\145\3\140\2\0\6\140\3\0\1\140"+
    "\1\0\2\140\1\146\5\140\6\0\1\140\6\0\4\140"+
    "\2\0\6\140\3\0\1\140\1\0\10\140\6\0\1\140"+
    "\6\0\4\140\2\0\6\140\2\0\1\147\1\140\1\0"+
    "\10\140\6\0\1\140\6\0\1\150\3\140\2\0\6\140"+
    "\3\0\1\140\1\0\10\140\6\0\1\140\6\0\4\140"+
    "\2\0\2\140\1\151\3\140\3\0\1\140\1\0\10\140"+
    "\6\0\1\140\6\0\3\140\1\152\2\0\6\140\3\0"+
    "\1\140\1\0\10\140\6\0\1\140\6\0\1\153\3\140"+
    "\2\0\6\140\3\0\1\140\1\0\4\140\1\154\3\140"+
    "\6\0\1\140\6\0\4\140\2\0\6\140\3\0\1\140"+
    "\1\0\10\140\6\0\1\140\6\0\2\140\1\155\1\140"+
    "\2\0\6\140\3\0\1\140\1\0\10\156\6\0\1\156"+
    "\6\0\4\156\2\0\6\156\3\0\1\156\1\0\10\156"+
    "\6\0\1\156\6\0\1\157\3\156\2\0\6\156\3\0"+
    "\1\156\1\0\2\156\1\160\5\156\6\0\1\156\6\0"+
    "\4\156\2\0\6\156\3\0\1\156\1\0\10\156\6\0"+
    "\1\156\6\0\1\161\3\156\2\0\6\156\3\0\1\156"+
    "\41\0\1\162\5\0\3\156\1\163\4\156\6\0\1\156"+
    "\6\0\4\156\2\0\6\156\3\0\1\156\1\0\10\156"+
    "\6\0\1\156\6\0\1\164\3\156\2\0\6\156\3\0"+
    "\1\156\1\0\10\156\6\0\1\156\6\0\1\165\3\156"+
    "\2\0\6\156\3\0\1\156\1\0\10\156\6\0\1\156"+
    "\6\0\4\156\2\0\5\156\1\166\3\0\1\156\1\0"+
    "\6\156\1\167\1\156\6\0\1\156\6\0\4\156\2\0"+
    "\6\156\3\0\1\156\1\0\10\170\6\0\1\170\6\0"+
    "\4\170\2\0\6\170\3\0\1\170\1\0\2\170\1\171"+
    "\5\170\6\0\1\170\6\0\4\170\2\0\6\170\3\0"+
    "\1\170\7\0\1\172\37\0\6\170\1\173\1\170\6\0"+
    "\1\170\6\0\4\170\2\0\6\170\3\0\1\170\1\0"+
    "\6\170\1\174\1\170\6\0\1\170\6\0\4\170\2\0"+
    "\6\170\3\0\1\170\1\0\2\170\1\175\5\170\6\0"+
    "\1\170\6\0\4\170\2\0\6\170\3\0\1\170\1\0"+
    "\10\176\6\0\1\176\6\0\4\176\2\0\6\176\3\0"+
    "\1\176\26\0\1\177\20\0\10\176\6\0\1\176\6\0"+
    "\1\200\3\176\2\0\6\176\3\0\1\176\1\0\10\201"+
    "\6\0\1\201\6\0\4\201\2\0\6\201\3\0\1\201"+
    "\1\0\10\202\6\0\1\202\6\0\4\202\2\0\6\202"+
    "\3\0\1\202\1\0\10\203\6\0\1\203\6\0\4\203"+
    "\2\0\6\203\3\0\1\203\1\0\10\204\6\0\1\204"+
    "\6\0\4\204\2\0\6\204\3\0\1\204\1\0\10\205"+
    "\6\0\1\205\6\0\4\205\2\0\6\205\3\0\1\205"+
    "\1\0\10\206\6\0\1\206\6\0\4\206\2\0\6\206"+
    "\3\0\1\206\1\0\10\207\6\0\1\207\6\0\4\207"+
    "\2\0\6\207\3\0\1\207\1\0\10\210\6\0\1\210"+
    "\6\0\4\210\2\0\6\210\3\0\1\210\1\0\10\211"+
    "\6\0\1\211\6\0\4\211\2\0\6\211\3\0\1\211"+
    "\1\0\10\212\6\0\1\212\6\0\4\212\2\0\6\212"+
    "\3\0\1\212\1\0\10\213\6\0\1\213\6\0\4\213"+
    "\2\0\6\213\3\0\1\213\1\0\10\214\6\0\1\214"+
    "\6\0\4\214\2\0\6\214\3\0\1\214\1\0\10\215"+
    "\6\0\1\215\6\0\4\215\2\0\6\215\3\0\1\215"+
    "\1\0\10\216\6\0\1\216\6\0\4\216\2\0\6\216"+
    "\3\0\1\216\1\0\10\217\6\0\1\217\6\0\4\217"+
    "\2\0\6\217\3\0\1\217\1\0\10\220\6\0\1\220"+
    "\6\0\4\220\2\0\6\220\3\0\1\220\1\0\10\221"+
    "\6\0\1\221\6\0\4\221\2\0\6\221\3\0\1\221"+
    "\1\0\10\222\6\0\1\222\6\0\4\222\2\0\6\222"+
    "\3\0\1\222\1\0\10\223\6\0\1\223\6\0\4\223"+
    "\2\0\6\223\3\0\1\223\1\0\10\224\6\0\1\224"+
    "\6\0\4\224\2\0\6\224\3\0\1\224\1\0\10\225"+
    "\6\0\1\225\6\0\4\225\2\0\6\225\3\0\1\225"+
    "\1\0\10\226\6\0\1\226\6\0\4\226\2\0\6\226"+
    "\3\0\1\226\1\0\10\227\6\0\1\227\6\0\4\227"+
    "\2\0\6\227\3\0\1\227";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4408];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\10\1\1\11\2\1\4\11\4\1\2\11"+
    "\3\1\2\11\13\1\1\0\2\1\3\11\14\1\1\11"+
    "\53\1\1\0\12\1\1\0\7\1\1\0\4\1\1\11"+
    "\27\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn) ;
  }

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value) ;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalyseurLexical(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {         return symbol(CodesLexicaux.EOF) ;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 41: break;
          case 2: 
            { return symbol(CodesLexicaux.CONSTANTEINT, yytext());
            }
          case 42: break;
          case 3: 
            { return symbol(CodesLexicaux.IDFTERM, yytext()) ;
            }
          case 43: break;
          case 4: 
            { return symbol(CodesLexicaux.DIV);
            }
          case 44: break;
          case 5: 
            { return symbol(CodesLexicaux.MULT);
            }
          case 45: break;
          case 6: 
            { return symbol(CodesLexicaux.EGAL);
            }
          case 46: break;
          case 7: 
            { return symbol(CodesLexicaux.INF);
            }
          case 47: break;
          case 8: 
            { return symbol(CodesLexicaux.SUP);
            }
          case 48: break;
          case 9: 
            { return symbol(CodesLexicaux.PLUS);
            }
          case 49: break;
          case 10: 
            { return symbol(CodesLexicaux.MOINS);
            }
          case 50: break;
          case 11: 
            { return symbol(CodesLexicaux.PAROUV);
            }
          case 51: break;
          case 12: 
            { return symbol(CodesLexicaux.PARFER);
            }
          case 52: break;
          case 13: 
            { return symbol(CodesLexicaux.POINTVIRGULE);
            }
          case 53: break;
          case 14: 
            { return symbol(CodesLexicaux.VIRGULE);
            }
          case 54: break;
          case 15: 
            { String s = yytext();
                            s = s.replace("\"\"", "\\\"");
                            return symbol(CodesLexicaux.CONSTANTECHAINE, s);
            }
          case 55: break;
          case 16: 
            { yybegin(commentaire);
            }
          case 56: break;
          case 17: 
            { return symbol(CodesLexicaux.EGALEGAL);
            }
          case 57: break;
          case 18: 
            { return symbol(CodesLexicaux.DIFF);
            }
          case 58: break;
          case 19: 
            { return symbol(CodesLexicaux.ET);
            }
          case 59: break;
          case 20: 
            { return symbol(CodesLexicaux.OU);
            }
          case 60: break;
          case 21: 
            { return symbol(CodesLexicaux.SI );
            }
          case 61: break;
          case 22: 
            { yybegin(YYINITIAL);
            }
          case 62: break;
          case 23: 
            { return symbol(CodesLexicaux.FIN );
            }
          case 63: break;
          case 24: 
            { return symbol(CodesLexicaux.FSI );
            }
          case 64: break;
          case 25: 
            { return symbol(CodesLexicaux.NON);
            }
          case 65: break;
          case 26: 
            { return symbol(CodesLexicaux.CONSTANTEBOOL, yytext());
            }
          case 66: break;
          case 27: 
            { return symbol(CodesLexicaux.POUR);
            }
          case 67: break;
          case 28: 
            { return symbol(CodesLexicaux.ALORS );
            }
          case 68: break;
          case 29: 
            { return symbol(CodesLexicaux.FTANT);
            }
          case 69: break;
          case 30: 
            { return symbol(CodesLexicaux.FPOUR);
            }
          case 70: break;
          case 31: 
            { return symbol(CodesLexicaux.SINON );
            }
          case 71: break;
          case 32: 
            { return symbol(CodesLexicaux.ENTIER);
            }
          case 72: break;
          case 33: 
            { return symbol(CodesLexicaux.ECRIRETERM);
            }
          case 73: break;
          case 34: 
            { return symbol(CodesLexicaux.CLASSETERM );
            }
          case 74: break;
          case 35: 
            { return symbol(CodesLexicaux.PRIVEE);
            }
          case 75: break;
          case 36: 
            { return symbol(CodesLexicaux.REPETER);
            }
          case 76: break;
          case 37: 
            { return symbol(CodesLexicaux.NOUVEAU );
            }
          case 77: break;
          case 38: 
            { return symbol(CodesLexicaux.DEBPOUR);
            }
          case 78: break;
          case 39: 
            { return symbol(CodesLexicaux.TANTQUE);
            }
          case 79: break;
          case 40: 
            { return symbol(CodesLexicaux.PUBLIQUE);
            }
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
