
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 13 14:28:07 CET 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FSI = 18;
  public static final int TANTQUE = 19;
  public static final int IDFTERM = 36;
  public static final int CONSTANTECHAINE = 37;
  public static final int MULT = 4;
  public static final int EGAL = 35;
  public static final int POUR = 22;
  public static final int REPETER = 21;
  public static final int SI = 15;
  public static final int VIRGULE = 29;
  public static final int FIN = 31;
  public static final int OU = 13;
  public static final int INF = 9;
  public static final int NON = 14;
  public static final int PAROUV = 6;
  public static final int DIV = 5;
  public static final int EGALEGAL = 10;
  public static final int PLUS = 2;
  public static final int FTANT = 20;
  public static final int CLASSETERM = 30;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOINS = 3;
  public static final int ET = 12;
  public static final int PRIVEE = 33;
  public static final int SINON = 16;
  public static final int ALORS = 17;
  public static final int PARFER = 7;
  public static final int CONSTANTEINT = 25;
  public static final int CONSTANTEBOOL = 26;
  public static final int POINTVIRGULE = 28;
  public static final int SUP = 8;
  public static final int DEBPOUR = 23;
  public static final int PUBLIQUE = 32;
  public static final int ECRIRETERM = 27;
  public static final int DIFF = 11;
  public static final int ENTIER = 34;
  public static final int FPOUR = 24;
}

