
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 13 08:34:21 CET 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int PLUSPLUS = 8;
  public static final int FSI = 20;
  public static final int TANTQUE = 21;
  public static final int IDFTERM = 38;
  public static final int CONSTANTECHAINE = 39;
  public static final int MULT = 4;
  public static final int EGAL = 37;
  public static final int POUR = 24;
  public static final int REPETER = 23;
  public static final int SI = 17;
  public static final int VIRGULE = 31;
  public static final int FIN = 33;
  public static final int OU = 15;
  public static final int INF = 11;
  public static final int NON = 16;
  public static final int PAROUV = 6;
  public static final int DIV = 5;
  public static final int EGALEGAL = 12;
  public static final int PLUS = 2;
  public static final int FTANT = 22;
  public static final int CLASSETERM = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOINS = 3;
  public static final int ET = 14;
  public static final int PRIVEE = 35;
  public static final int SINON = 18;
  public static final int ALORS = 19;
  public static final int PARFER = 7;
  public static final int CONSTANTEINT = 27;
  public static final int CONSTANTEBOOL = 28;
  public static final int POINTVIRGULE = 30;
  public static final int SUP = 10;
  public static final int DEBPOUR = 25;
  public static final int PUBLIQUE = 34;
  public static final int ECRIRETERM = 29;
  public static final int DIFF = 13;
  public static final int ENTIER = 36;
  public static final int FPOUR = 26;
  public static final int MOINSMOINS = 9;
}

